import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TicketDialogContextProvider } from './contexts/TicketDialogContext'
import { RegisterDialogContextProvider } from './contexts/RegisterDialogContext'

const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '600'] })

export const metadata: Metadata = {
  title: 'PayFlow',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TicketDialogContextProvider>
          <RegisterDialogContextProvider>
            {children}
          </RegisterDialogContextProvider>
        </TicketDialogContextProvider>
      </body>
    </html>
  )
}
